"""Autogenerated CLI smoke tests (do not edit manually).

These tests are intentionally lightweight but exercise the CLI against the
canonical fixtures so Copilot can regenerate them on demand. Regenerate via:
    python3 tools/vectorscan/copilot_suite_generator.py
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
CLI_PATH = REPO_ROOT / "tools" / "vectorscan" / "vectorscan.py"
FIXTURES = REPO_ROOT / "tests" / "fixtures"


def _run_cli(fixture_name: str, *flags: str) -> subprocess.CompletedProcess[str]:
    fixture_path = FIXTURES / fixture_name
    assert fixture_path.exists(), fixture_path
    env = os.environ.copy()
    env.setdefault("VSCAN_OFFLINE", "1")
    env.setdefault("VSCAN_CLOCK_ISO", "2024-01-01T00:00:00Z")
    env.setdefault("VSCAN_CLOCK_EPOCH", "1704067200")
    env.setdefault("VSCAN_NO_COLOR", "1")
    cmd = [sys.executable, str(CLI_PATH), str(fixture_path), *flags]
    return subprocess.run(cmd, capture_output=True, text=True, check=False, env=env)


def test_pass_fixture_returns_zero() -> None:
    result = _run_cli("tfplan_pass.json", "--json")
    assert result.returncode == 0, result.stderr
    payload = json.loads(result.stdout)
    assert payload["status"] == "PASS"
    assert payload["metrics"]["compliance_score"] == pytest.approx(100.0)


def test_fail_fixture_returns_three() -> None:
    result = _run_cli("tfplan_fail.json", "--json")
    assert result.returncode == 3, result.stdout
    payload = json.loads(result.stdout)
    assert payload["status"] == "FAIL"
    violations_struct = payload.get("violations_struct", [])
    assert any(v.get("policy_id") == "P-SEC-001" for v in violations_struct)
